//! Generate TypeScript types + Zod schemas from Rust models.
//!
//! Mirrors the legacy `generate_types` binary that used to live under
//! `crates/remargin/src/bin/`. Moving it here ensures `cargo install
//! remargin` no longer pollutes `~/.cargo/bin/` with a dev-time tool.

use std::fs;
use std::path::Path;

use anyhow::{Context as _, Result};
use remargin_core::activity::{compact_change_row_schema, compact_file_changes_schema};
use remargin_core::config::registry::{participant_status_schema, participant_view_schema};
use remargin_core::document::list_entry_schema;
use remargin_core::on_disk_comment::{on_disk_comment_schema, reaction_entry_on_disk_schema};
use remargin_core::operations::cp::{cp_kind_schema, cp_outcome_schema};
use remargin_core::operations::links::{
    compact_link_row_schema, compact_links_schema, link_schema,
};
use remargin_core::operations::query::{
    compact_comment_row_schema, compact_query_result_schema, expanded_comment_schema,
    query_result_schema,
};
use remargin_core::operations::replace::{replace_file_outcome_schema, replace_report_schema};
use remargin_core::operations::sandbox::{
    sandbox_failure_entry_schema, sandbox_list_entry_schema, sandbox_remove_report_schema,
};
use remargin_core::operations::search::{
    compact_file_matches_schema, compact_match_row_schema, match_location_schema,
    search_hit_location_schema, search_match_schema,
};
use remargin_core::operations::verify::{
    verify_error_kind_schema, verify_failure_payload_schema, verify_failure_row_schema,
};
use remargin_core::parser::{acknowledgment_schema, author_type_schema, comment_schema};
use remargin_core::permissions::doctor::{
    doctor_finding_schema, doctor_report_schema, finding_kind_schema, severity_schema,
};
use remargin_core::reactions::reaction_entry_schema;

/// Pair a registered schema module with its wire [`Shape`], so the
/// classification reads as one line per entry next to the registration.
macro_rules! registration {
    ($shape:ident, $module:ident) => {
        (
            Shape::$shape,
            $module::Schema::ts_definition(),
            $module::Schema::zod_schema(),
        )
    };
}

/// Preamble for `schemas.ts`: the zod import plus the `import type` block
/// naming every generated TS type. Kept here so [`run`] stays under the
/// line cap; the type list order is cosmetic (imports hoist).
///
/// `ZodType` is imported unqualified because that is how `model_schema!`
/// spells the exported binding it emits below the header
/// (`export const Foo$Schema: ZodType<Foo> = Foo$RawSchema;`). It only
/// becomes droppable if tixschema starts namespacing that annotation
/// through `z`.
const SCHEMAS_HEADER: &str = "// Auto-generated by generate_types. Do not edit.\n\n\
     import { z, type ZodType } from \"zod/v4\";\n\
     import type {\n  \
       AuthorType,\n  \
       Acknowledgment,\n  \
       ReactionEntry,\n  \
       ReactionEntryOnDisk,\n  \
       Comment,\n  \
       OnDiskComment,\n  \
       ListEntry,\n  \
       ExpandedComment,\n  \
       QueryResult,\n  \
       CompactCommentRow,\n  \
       CompactQueryResult,\n  \
       CompactChangeRow,\n  \
       CompactFileChanges,\n  \
       MatchLocation,\n  \
       SearchMatch,\n  \
       SearchHitLocation,\n  \
       CompactMatchRow,\n  \
       CompactFileMatches,\n  \
       ReplaceFileOutcome,\n  \
       ReplaceReport,\n  \
       CpKind,\n  \
       CpOutcome,\n  \
       Link,\n  \
       CompactLinkRow,\n  \
       CompactLinks,\n  \
       SandboxFailureEntry,\n  \
       SandboxListEntry,\n  \
       SandboxRemoveReport,\n  \
       ParticipantStatus,\n  \
       ParticipantView,\n  \
       VerifyErrorKind,\n  \
       VerifyFailureRow,\n  \
       VerifyFailurePayload,\n  \
       Severity,\n  \
       FindingKind,\n  \
       DoctorFinding,\n  \
       DoctorReport,\n\
     } from \"./types\";\n\n";

/// The `elapsed_ms` the io layer injects is a `u64` millisecond count and
/// is absent from any payload the CLI did not decorate, so it is optional
/// and never nullable.
const TS_ELAPSED_MS_MEMBER: &str = "  elapsed_ms?: number;\n";
const ZOD_ELAPSED_MS_MEMBER: &str = "  elapsed_ms: z.number().optional(),\n";

/// Where a registered schema sits on the wire.
///
/// `crates/remargin/src/io.rs` decorates every top-level `--json` payload
/// with an injected `elapsed_ms` on the way out (the MCP `tools/call`
/// path does the same), so a schema modelling a whole payload has to
/// admit that key while staying strict about every other unknown one. A
/// `Nested` schema only ever appears inside a payload and never sees it.
enum Shape {
    Nested,
    Report,
}

/// Run the type + schema generator, writing into
/// `packages/remargin-obsidian/src/generated/` relative to the repo
/// root. The working directory is expected to be the workspace root —
/// the justfile / pnpm scripts take care of that.
pub fn run() -> Result<()> {
    let out_dir = Path::new("packages/remargin-obsidian/src/generated");
    fs::create_dir_all(out_dir)
        .with_context(|| format!("creating output directory {}", out_dir.display()))?;

    // Order matters: dependencies first. The `Report` / `Nested` tag on
    // each entry is the wire classification — see [`Shape`].
    let registry = [
        registration!(Nested, author_type_schema),
        registration!(Nested, acknowledgment_schema),
        registration!(Nested, reaction_entry_schema),
        registration!(Nested, reaction_entry_on_disk_schema),
        registration!(Nested, comment_schema),
        registration!(Nested, on_disk_comment_schema),
        registration!(Nested, list_entry_schema),
        registration!(Nested, expanded_comment_schema),
        registration!(Nested, query_result_schema),
        registration!(Nested, compact_comment_row_schema),
        registration!(Nested, compact_query_result_schema),
        registration!(Nested, compact_change_row_schema),
        registration!(Nested, compact_file_changes_schema),
        registration!(Nested, match_location_schema),
        registration!(Nested, search_match_schema),
        registration!(Nested, search_hit_location_schema),
        registration!(Nested, compact_match_row_schema),
        registration!(Nested, compact_file_matches_schema),
        registration!(Nested, replace_file_outcome_schema),
        registration!(Report, replace_report_schema),
        registration!(Nested, cp_kind_schema),
        registration!(Report, cp_outcome_schema),
        registration!(Nested, link_schema),
        registration!(Nested, compact_link_row_schema),
        registration!(Nested, compact_links_schema),
        registration!(Nested, sandbox_failure_entry_schema),
        registration!(Nested, sandbox_list_entry_schema),
        registration!(Report, sandbox_remove_report_schema),
        registration!(Nested, participant_status_schema),
        registration!(Nested, participant_view_schema),
        registration!(Nested, verify_error_kind_schema),
        registration!(Nested, verify_failure_row_schema),
        registration!(Report, verify_failure_payload_schema),
        registration!(Nested, severity_schema),
        registration!(Nested, finding_kind_schema),
        registration!(Nested, doctor_finding_schema),
        registration!(Report, doctor_report_schema),
    ];

    let mut types_content = String::from("// Auto-generated by generate_types. Do not edit.\n\n");
    let mut schemas_content = String::from(SCHEMAS_HEADER);
    for (shape, ts_def, zod_def) in registry {
        match shape {
            Shape::Nested => {
                types_content.push_str(&ts_def);
                schemas_content.push_str(&zod_def);
            }
            Shape::Report => {
                types_content.push_str(&with_elapsed_ms_member(&ts_def)?);
                schemas_content.push_str(&with_elapsed_ms_key(&zod_def)?);
            }
        }
        types_content.push('\n');
        schemas_content.push('\n');
    }

    write_file(&out_dir.join("types.ts"), &types_content)?;
    write_file(&out_dir.join("schemas.ts"), &schemas_content)?;

    let index_content = "// Auto-generated by generate_types. Do not edit.\n\n\
         export * from \"./types\";\n\
         export * from \"./schemas\";\n";
    write_file(&out_dir.join("index.ts"), index_content)?;

    println!("Generated types in {}", out_dir.display());
    Ok(())
}

fn write_file(path: &Path, content: &str) -> Result<()> {
    fs::write(path, content).with_context(|| format!("writing {}", path.display()))?;
    println!("  wrote {}", path.display());
    Ok(())
}

/// Add the optional `elapsed_ms` to a [`Shape::Report`] TypeScript type.
fn with_elapsed_ms_member(definition: &str) -> Result<String> {
    splice_first_member(definition, TS_ELAPSED_MS_MEMBER, |line| {
        line.starts_with("export type ") && line.ends_with("= {")
    })
    .context("report schema emits no `export type ... = {` body to extend")
}

/// Add the optional `elapsed_ms` to a [`Shape::Report`] Zod schema. The
/// key goes inside the existing `strictObject` literal, so every other
/// unknown key stays rejected.
fn with_elapsed_ms_key(definition: &str) -> Result<String> {
    splice_first_member(definition, ZOD_ELAPSED_MS_MEMBER, |line| {
        line.starts_with("const ") && line.ends_with("z.strictObject({")
    })
    .context("report schema emits no `z.strictObject({` literal to extend")
}

/// Insert `member` as the first line of the object body opened by the
/// first line `is_opener` accepts. `None` when no line matches — a
/// registration tagged [`Shape::Report`] whose schema is not an object.
fn splice_first_member<F>(definition: &str, member: &str, is_opener: F) -> Option<String>
where
    F: Fn(&str) -> bool,
{
    let mut out = String::with_capacity(definition.len() + member.len());
    let mut spliced = false;
    for line in definition.split_inclusive('\n') {
        out.push_str(line);
        if !spliced && is_opener(line.trim_end()) {
            out.push_str(member);
            spliced = true;
        }
    }
    spliced.then_some(out)
}
